title: "4시간 BTC 예측 토론"
labels: ["prediction", "discussion"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📊 시장 분석
        현재 시장 상황과 예측 근거를 공유해주세요.
        
  - type: textarea
    id: analysis
    attributes:
      label: 분석 내용
      description: "기술적/펀더멘탈 분석을 자유롭게 공유해주세요"
      placeholder: "예) 현재 4시간 차트에서 볼린저 밴드가..."
    validations:
      required: true
      
  - type: dropdown
    id: direction
    attributes:
      label: 예상 방향
      options:
        - 상승
        - 하락
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: 추가 의견
      description: "다른 트레이더들과 공유하고 싶은 의견이 있다면 작성해주세요"
      placeholder: "추가 의견을 작성해주세요" 