name: "4시간 BTC 방향성 예측"
description: "다음 4시간 봉의 BTC 가격 방향성 예측 투표"
title: "[4H Poll] BTCUSDT 방향성 예측 (<날짜> <시간>)"
labels: ["prediction", "active"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📊 4시간 방향성 투표
        
        ### ⏰ 투표 기간
        - 시작: <시작 시간>
        - 마감: <마감 시간>
        
        ### 📈 현재 가격: $<가격>
        
        ### 투표 방법
        - 👍 (상승 예상)
        - 👎 (하락 예상)
        
        ### 분석 공유
        - 코멘트로 자유롭게 분석을 공유해주세요
        - 기술적/펀더멘탈 분석 모두 환영합니다
        
        ### 결과 집계
        - 4시간 후 종가 기준으로 판정
        - 시작 가격 대비 +/- 로 승패 결정
        - 정확도는 Wiki 페이지에서 확인 가능
        
        ### 주의사항
        - 마감 전까지 예측을 변경할 수 있습니다
        - 여러 번 투표 시 마지막 투표만 인정
        - 결과는 자동으로 집계됩니다
        
        ### 토론 참여
        - [토론방 바로가기](링크) 에서 자유롭게 의견을 나눠주세요! 